---
name: "Simkl Sync"
guid: "A1B2C3D4-E5F6-7890-ABCD-EF1234567890"
version: 1
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "infinitygp"
overview: "Simkl plugin with full sync support"
description: >
  Simkl plugin with full two-way synchronization support. Scrobble and sync your watched Movies, TV Shows and Anime to Simkl.

category: "General"
artifacts:
  - "Jellyfin.Plugin.Simkl.dll"
changelog: |-
  - Added full two-way synchronization
  - Import watch history from SIMKL
  - Export library to SIMKL
  - Real-time sync on user data changes
  - Real-time sync on library changes
